// <auto-generated />
using System;
using Member.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Member.Migrations
{
    [DbContext(typeof(MemberContext))]
    [Migration("20220910044339_Fk_Personallist")]
    partial class Fk_Personallist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Member.Context.Memberlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Entryby")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ENTRYBY");

                    b.Property<DateTime?>("Entrydate")
                        .HasColumnType("datetime")
                        .HasColumnName("ENTRYDATE");

                    b.Property<long?>("Idpersonal")
                        .HasColumnType("bigint")
                        .HasColumnName("IDPERSONAL");

                    b.Property<double?>("Totalpremium")
                        .HasColumnType("float")
                        .HasColumnName("TOTALPREMIUM");

                    b.HasKey("Id");

                    b.HasIndex("Idpersonal");

                    b.ToTable("MEMBERLIST", (string)null);
                });

            modelBuilder.Entity("Member.Context.Personallist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Entryby")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ENTRYBY");

                    b.Property<DateTime?>("Entrydate")
                        .HasColumnType("datetime")
                        .HasColumnName("ENTRYDATE");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("datetime")
                        .HasColumnName("STARTDATE");

                    b.HasKey("Id");

                    b.ToTable("PERSONALLIST", (string)null);
                });

            modelBuilder.Entity("Member.Context.Memberlist", b =>
                {
                    b.HasOne("Member.Context.Personallist", "IdpersonalNavigation")
                        .WithMany("Memberlists")
                        .HasForeignKey("Idpersonal")
                        .HasConstraintName("MEMBER_PERSON");

                    b.Navigation("IdpersonalNavigation");
                });

            modelBuilder.Entity("Member.Context.Personallist", b =>
                {
                    b.Navigation("Memberlists");
                });
#pragma warning restore 612, 618
        }
    }
}
